// enums/estadosMx.enum.js

/**
 * @enum {string} EstadosMexico
 * @description Enumera los estados de México.
 */
const EstadosMexico = {
    AGUASCALIENTES: 'AGUASCALIENTES',
    BAJA_CALIFORNIA: 'BAJA_CALIFORNIA',
    BAJA_CALIFORNIA_SUR: 'BAJA_CALIFORNIA_SUR',
    CAMPECHE: 'CAMPECHE',
    CHIAPAS: 'CHIAPAS',
    CHIHUAHUA: 'CHIHUAHUA',
    CIUDAD_DE_MEXICO: 'CIUDAD_DE_MEXICO',
    COAHUILA: 'COAHUILA',
    COLIMA: 'COLIMA',
    DURANGO: 'DURANGO',
    ESTADO_DE_MEXICO: 'ESTADO_DE_MEXICO',
    GUANAJUATO: 'GUANAJUATO',
    GUERRERO: 'GUERRERO',
    HIDALGO: 'HIDALGO',
    JALISCO: 'JALISCO',
    MICHOACAN: 'MICHOACAN',
    MORELOS: 'MORELOS',
    NAYARIT: 'NAYARIT',
    NUEVO_LEON: 'NUEVO_LEON',
    OAXACA: 'OAXACA',
    PUEBLA: 'PUEBLA',
    QUERETARO: 'QUERETARO',
    QUINTANA_ROO: 'QUINTANA_ROO',
    SAN_LUIS_POTOSI: 'SAN_LUIS_POTOSI',
    SINALOA: 'SINALOA',
    SONORA: 'SONORA',
    TABASCO: 'TABASCO',
    TAMAULIPAS: 'TAMAULIPAS',
    TLAXCALA: 'TLAXCALA',
    VERACRUZ: 'VERACRUZ',
    YUCATAN: 'YUCATAN',
    ZACATECAS: 'ZACATECAS'
};

module.exports = EstadosMexico;