  // tipodocumento.enum.js

  const TipoDocumento = Object.freeze({
    ACTA_NACIMIENTO: 'ACTA_NACIMIENTO',
    APROBACION_PERMISO: 'APROBACION_PERMISO',
    CERTIFICADO_ESTUDIO: 'CERTIFICADO_ESTUDIO',
    CONSTANCIA_DOCUMENTOS_COMPROBATORIOS: 'CONSTANCIA_DOCUMENTOS_COMPROBATORIOS',
    CONSTANCIA_NOMBRAMIENTO: 'CONSTANCIA_NOMBRAMIENTO',
    CONSTANCIA_RECONOCIMIENTO: 'CONSTANCIA_RECONOCIMIENTO',
    CURP: 'CURP',
    INE: 'INE',
    OFICIO: 'OFICIO',
    RFC: 'RFC',
    OTRO_DOCUMENTO: 'OTRO_DOCUMENTO',

    // Nuevos tipos usados en trabajadores_cursos
    INVITACION_CURSO: 'INVITACION_CURSO',
    CONCLUSION_CURSO: 'CONCLUSION_CURSO',
    CERTIFICADO_CURSO: 'CERTIFICADO_CURSO'
  });

  module.exports = TipoDocumento;
